### PR TITLE
Make all dependencies devDependencies.

### LINKED ISSUE #1: Move deps to devDependencies?
Heh.

Sorry for being a nag, but here the reverse problem occurs: all deps are listed as `dependencies`, hence installing this package also installs `webpack` and `@babel/*`, which are quite large.

Seems like they are not needed when consuming the runtime version of this package.

### PR DESCRIPTION
**Pull request by corwin-of-amber**
Closes #1.

### CODE REVIEW

**Comment by andersevenrud** [comment]
Much appreciated! I published a new release with these changes to npm.

**Comment by corwin-of-amber** [comment]
Uhm I think that the new NPM package is missing the build directory `dist/`. Perhaps the prepublish script failed because webpack was missing now..?
```sh
% npm i simplejsonconf
+ simplejsonconf@2.0.6
added 1 package from 1 contributor and audited 1 package in 1.475s
% ls node_modules/simplejsonconf
README.md    package.json
```

**Comment by andersevenrud** [comment]
Woah. That's a bit strange.... I published the package with the `dist/` directory from the previous build! I'm on it. Thanks!

**Comment by andersevenrud** [comment]
Note to self: don't do stuff when sick and have a massive fever. Things go wrong!

Of course this failed... the prepublish npm script removes the build output :(

 I need to move this process to Github Actions with a validation process.

**Comment by corwin-of-amber** [comment]
Oh no! Get well soon!! ❤️

**Comment by andersevenrud** [comment]
Thanks! I caught some nasty virus this Christmas and my immune system still hasn't sorted it out :laughing:

**Comment by corwin-of-amber** [comment]
Here's a nugget for you to cheer you up 😄 
https://basin.now.sh/
It's what I've been doing with OS.js.
🎁

**Comment by andersevenrud** [comment]
Nice! :ok_hand:  That's the first time I've seen someone use WebAssembly in OS.js in the wild!

**Pull request merged**
